// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: common/v1/types.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_UNSPECIFIED DeviceType = 0
	DeviceType_DEVICE_TYPE_MOBILE      DeviceType = 1
	DeviceType_DEVICE_TYPE_TABLET      DeviceType = 2
	DeviceType_DEVICE_TYPE_PC          DeviceType = 3
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "DEVICE_TYPE_MOBILE",
		2: "DEVICE_TYPE_TABLET",
		3: "DEVICE_TYPE_PC",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"DEVICE_TYPE_MOBILE":      1,
		"DEVICE_TYPE_TABLET":      2,
		"DEVICE_TYPE_PC":          3,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_types_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_common_v1_types_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{0}
}

// 消息的指令类型。
type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED CommandType = 0
	// 心跳指令。
	CommandType_COMMAND_TYPE_HEARTBEAT CommandType = 1
	// 上行消息:  frontend -> gateway -> backend。
	CommandType_COMMAND_TYPE_UPSTREAM CommandType = 2
	// 上行消息 ack: gateway -> frontend。
	CommandType_COMMAND_TYPE_UPSTREAM_ACK CommandType = 3
	// 下行消息: backend -> gateway -> frontend。
	CommandType_COMMAND_TYPE_DOWNSTREAM CommandType = 4
	// 下行消息: frontend -> gateway。
	CommandType_COMMAND_TYPE_DOWNSTREAM_ACK CommandType = 5
	// 重定向指令。
	CommandType_COMMAND_TYPE_REDIRECT CommandType = 6
	// 限流指令：gateway -> frontend。
	CommandType_COMMAND_TYPE_RATE_LIMIT_EXCEEDED CommandType = 7
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_HEARTBEAT",
		2: "COMMAND_TYPE_UPSTREAM",
		3: "COMMAND_TYPE_UPSTREAM_ACK",
		4: "COMMAND_TYPE_DOWNSTREAM",
		5: "COMMAND_TYPE_DOWNSTREAM_ACK",
		6: "COMMAND_TYPE_REDIRECT",
		7: "COMMAND_TYPE_RATE_LIMIT_EXCEEDED",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":         0,
		"COMMAND_TYPE_HEARTBEAT":           1,
		"COMMAND_TYPE_UPSTREAM":            2,
		"COMMAND_TYPE_UPSTREAM_ACK":        3,
		"COMMAND_TYPE_DOWNSTREAM":          4,
		"COMMAND_TYPE_DOWNSTREAM_ACK":      5,
		"COMMAND_TYPE_REDIRECT":            6,
		"COMMAND_TYPE_RATE_LIMIT_EXCEEDED": 7,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_types_proto_enumTypes[1].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_common_v1_types_proto_enumTypes[1]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{1}
}

// 消息体的序列化类型。
// 目前只支持 protobuf 和 json 两种（生产环境推荐使用 protobuf）。
type SerializeType int32

const (
	SerializeType_SERIALIZE_TYPE_UNSPECIFIED SerializeType = 0
	SerializeType_SERIALIZE_TYPE_PROTOBUF    SerializeType = 1
	SerializeType_SERIALIZE_TYPE_JSON        SerializeType = 2
)

// Enum value maps for SerializeType.
var (
	SerializeType_name = map[int32]string{
		0: "SERIALIZE_TYPE_UNSPECIFIED",
		1: "SERIALIZE_TYPE_PROTOBUF",
		2: "SERIALIZE_TYPE_JSON",
	}
	SerializeType_value = map[string]int32{
		"SERIALIZE_TYPE_UNSPECIFIED": 0,
		"SERIALIZE_TYPE_PROTOBUF":    1,
		"SERIALIZE_TYPE_JSON":        2,
	}
)

func (x SerializeType) Enum() *SerializeType {
	p := new(SerializeType)
	*p = x
	return p
}

func (x SerializeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SerializeType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_types_proto_enumTypes[2].Descriptor()
}

func (SerializeType) Type() protoreflect.EnumType {
	return &file_common_v1_types_proto_enumTypes[2]
}

func (x SerializeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SerializeType.Descriptor instead.
func (SerializeType) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{2}
}

var File_common_v1_types_proto protoreflect.FileDescriptor

const file_common_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x15common/v1/types.proto\x12\tcommon.v1*m\n" +
	"\n" +
	"DeviceType\x12\x1b\n" +
	"\x17DEVICE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DEVICE_TYPE_MOBILE\x10\x01\x12\x16\n" +
	"\x12DEVICE_TYPE_TABLET\x10\x02\x12\x12\n" +
	"\x0eDEVICE_TYPE_PC\x10\x03*\x80\x02\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16COMMAND_TYPE_HEARTBEAT\x10\x01\x12\x19\n" +
	"\x15COMMAND_TYPE_UPSTREAM\x10\x02\x12\x1d\n" +
	"\x19COMMAND_TYPE_UPSTREAM_ACK\x10\x03\x12\x1b\n" +
	"\x17COMMAND_TYPE_DOWNSTREAM\x10\x04\x12\x1f\n" +
	"\x1bCOMMAND_TYPE_DOWNSTREAM_ACK\x10\x05\x12\x19\n" +
	"\x15COMMAND_TYPE_REDIRECT\x10\x06\x12$\n" +
	" COMMAND_TYPE_RATE_LIMIT_EXCEEDED\x10\a*e\n" +
	"\rSerializeType\x12\x1e\n" +
	"\x1aSERIALIZE_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SERIALIZE_TYPE_PROTOBUF\x10\x01\x12\x17\n" +
	"\x13SERIALIZE_TYPE_JSON\x10\x02B\x98\x01\n" +
	"\rcom.common.v1B\n" +
	"TypesProtoP\x01Z6github.com/jrmarcco/synp-api/api/go/common/v1;commonv1\xa2\x02\x03CXX\xaa\x02\tCommon.V1\xca\x02\tCommon\\V1\xe2\x02\x15Common\\V1\\GPBMetadata\xea\x02\n" +
	"Common::V1b\x06proto3"

var (
	file_common_v1_types_proto_rawDescOnce sync.Once
	file_common_v1_types_proto_rawDescData []byte
)

func file_common_v1_types_proto_rawDescGZIP() []byte {
	file_common_v1_types_proto_rawDescOnce.Do(func() {
		file_common_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_types_proto_rawDesc), len(file_common_v1_types_proto_rawDesc)))
	})
	return file_common_v1_types_proto_rawDescData
}

var file_common_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_v1_types_proto_goTypes = []any{
	(DeviceType)(0),    // 0: common.v1.DeviceType
	(CommandType)(0),   // 1: common.v1.CommandType
	(SerializeType)(0), // 2: common.v1.SerializeType
}
var file_common_v1_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_types_proto_init() }
func file_common_v1_types_proto_init() {
	if File_common_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_types_proto_rawDesc), len(file_common_v1_types_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_types_proto_goTypes,
		DependencyIndexes: file_common_v1_types_proto_depIdxs,
		EnumInfos:         file_common_v1_types_proto_enumTypes,
	}.Build()
	File_common_v1_types_proto = out.File
	file_common_v1_types_proto_goTypes = nil
	file_common_v1_types_proto_depIdxs = nil
}
