// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: message/v1/message.proto

package messagev1

import (
	v1 "github.com/jrmarcco/synp-api/api/go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushStatus int32

const (
	PushStatus_PUSH_STATUS_UNSPECIFIED     PushStatus = 0
	PushStatus_PUSH_STATUS_SUCCESS         PushStatus = 1 // 成功
	PushStatus_PUSH_STATUS_USER_OFFLINE    PushStatus = 2 // 用户离线
	PushStatus_PUSH_STATUS_RATE_LIMITED    PushStatus = 3 // 限流
	PushStatus_PUSH_STATUS_INVALID_MESSAGE PushStatus = 4 // 消息格式错误
	PushStatus_PUSH_STATUS_INTERNAL_ERROR  PushStatus = 5 // 内部错误
)

// Enum value maps for PushStatus.
var (
	PushStatus_name = map[int32]string{
		0: "PUSH_STATUS_UNSPECIFIED",
		1: "PUSH_STATUS_SUCCESS",
		2: "PUSH_STATUS_USER_OFFLINE",
		3: "PUSH_STATUS_RATE_LIMITED",
		4: "PUSH_STATUS_INVALID_MESSAGE",
		5: "PUSH_STATUS_INTERNAL_ERROR",
	}
	PushStatus_value = map[string]int32{
		"PUSH_STATUS_UNSPECIFIED":     0,
		"PUSH_STATUS_SUCCESS":         1,
		"PUSH_STATUS_USER_OFFLINE":    2,
		"PUSH_STATUS_RATE_LIMITED":    3,
		"PUSH_STATUS_INVALID_MESSAGE": 4,
		"PUSH_STATUS_INTERNAL_ERROR":  5,
	}
)

func (x PushStatus) Enum() *PushStatus {
	p := new(PushStatus)
	*p = x
	return p
}

func (x PushStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_v1_message_proto_enumTypes[0].Descriptor()
}

func (PushStatus) Type() protoreflect.EnumType {
	return &file_message_v1_message_proto_enumTypes[0]
}

func (x PushStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushStatus.Descriptor instead.
func (PushStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_v1_message_proto_rawDescGZIP(), []int{0}
}

// Message 是前端 ( 业务客户端 ) 和网关之间的通信消息。
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 由前端 ( 业务客户端 ) 生成，有 2 个作用:
	//
	//	1.消息去重。
	//	2.对 message_id 进行 hash，选择消息队列分区从而保证消息有序性。
	//
	// message_id 需要由前端生成 ( 建议使用 ULID )
	//
	//	npm install ulid
	//	或
	//	yarn add ulid
	//
	//	import { ulid } from 'ulid'
	//
	//	const messageId = ulid()
	//
	//	// 也支持从时间戳生成
	//	const messageId = ulid(Date.now())
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// 消息类型。
	// 这里不使用 type 作为字段名是因为 type 在 go 里面是关键字。
	CommandType v1.CommandType `protobuf:"varint,2,opt,name=command_type,json=commandType,proto3,enum=common.v1.CommandType" json:"command_type,omitempty"`
	// body 的序列化类型。
	SerializeType v1.SerializeType `protobuf:"varint,3,opt,name=serialize_type,json=serializeType,proto3,enum=common.v1.SerializeType" json:"serialize_type,omitempty"`
	// 消息体。
	Body          []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetCommandType() v1.CommandType {
	if x != nil {
		return x.CommandType
	}
	return v1.CommandType(0)
}

func (x *Message) GetSerializeType() v1.SerializeType {
	if x != nil {
		return x.SerializeType
	}
	return v1.SerializeType(0)
}

func (x *Message) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// AckPayload 是消息确认的载荷，包含消息的处理结果。
// 适用于上行消息和下行消息的 ACK 响应。
// 当 Message.command_type = COMMAND_TYPE_ACK 时，该消息会被序列化到 Message.body 中。
type AckPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息处理是否成功。
	IsSuccess bool `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	// 错误信息（ 仅在 success = false 时有值 ）。
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// 服务端处理时间戳 ( 毫秒 )。
	TimestampMs   int64 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckPayload) Reset() {
	*x = AckPayload{}
	mi := &file_message_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckPayload) ProtoMessage() {}

func (x *AckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckPayload.ProtoReflect.Descriptor instead.
func (*AckPayload) Descriptor() ([]byte, []int) {
	return file_message_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *AckPayload) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *AckPayload) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AckPayload) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// PushMessage 是由后端 ( 业务服务端 ) 主动向网关发送的消息。
// 通信方式为业务后端推送 PushMessage 到 Kafka 的指定 topic，由网关监听并消费。
// 网关收到 PushMessage 后，
// 会向前端发送 CommandType 为 COMMAND_TYPE_DOWNSTREAM 的 Message。
type PushMessage struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	MessageId  string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ReceiverId uint64                 `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	// body 的序列化类型。
	SerializeType v1.SerializeType `protobuf:"varint,3,opt,name=serialize_type,json=serializeType,proto3,enum=common.v1.SerializeType" json:"serialize_type,omitempty"`
	// 消息体。
	Body          []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	mi := &file_message_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_message_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *PushMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *PushMessage) GetReceiverId() uint64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *PushMessage) GetSerializeType() v1.SerializeType {
	if x != nil {
		return x.SerializeType
	}
	return v1.SerializeType(0)
}

func (x *PushMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type PushRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message *PushMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// 是否应该在失败时重试。
	ShouldRetry   bool `protobuf:"varint,2,opt,name=should_retry,json=shouldRetry,proto3" json:"should_retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_message_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_message_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *PushRequest) GetMessage() *PushMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PushRequest) GetShouldRetry() bool {
	if x != nil {
		return x.ShouldRetry
	}
	return false
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PushStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=message.v1.PushStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_message_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_message_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *PushResponse) GetStatus() PushStatus {
	if x != nil {
		return x.Status
	}
	return PushStatus_PUSH_STATUS_UNSPECIFIED
}

func (x *PushResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type BatchPushRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Messages []*PushMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// 预留字段。
	// 可选的回调地址 ( 用于结果通知 )。
	CallbackUrl   string `protobuf:"bytes,2,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPushRequest) Reset() {
	*x = BatchPushRequest{}
	mi := &file_message_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPushRequest) ProtoMessage() {}

func (x *BatchPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPushRequest.ProtoReflect.Descriptor instead.
func (*BatchPushRequest) Descriptor() ([]byte, []int) {
	return file_message_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *BatchPushRequest) GetMessages() []*PushMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *BatchPushRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

// BatchPushResponse 批量推送响应。
// 目前均为预留字段。
type BatchPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AcceptedCount int32                  `protobuf:"varint,2,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	RejectedCount int32                  `protobuf:"varint,3,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPushResponse) Reset() {
	*x = BatchPushResponse{}
	mi := &file_message_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPushResponse) ProtoMessage() {}

func (x *BatchPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPushResponse.ProtoReflect.Descriptor instead.
func (*BatchPushResponse) Descriptor() ([]byte, []int) {
	return file_message_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *BatchPushResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *BatchPushResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *BatchPushResponse) GetRejectedCount() int32 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

var File_message_v1_message_proto protoreflect.FileDescriptor

const file_message_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x18message/v1/message.proto\x12\n" +
	"message.v1\x1a\x15common/v1/types.proto\"\xb8\x01\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x129\n" +
	"\fcommand_type\x18\x02 \x01(\x0e2\x16.common.v1.CommandTypeR\vcommandType\x12?\n" +
	"\x0eserialize_type\x18\x03 \x01(\x0e2\x18.common.v1.SerializeTypeR\rserializeType\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\"s\n" +
	"\n" +
	"AckPayload\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\bR\tisSuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"\xa2\x01\n" +
	"\vPushMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\x04R\n" +
	"receiverId\x12?\n" +
	"\x0eserialize_type\x18\x03 \x01(\x0e2\x18.common.v1.SerializeTypeR\rserializeType\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\"c\n" +
	"\vPushRequest\x121\n" +
	"\amessage\x18\x01 \x01(\v2\x17.message.v1.PushMessageR\amessage\x12!\n" +
	"\fshould_retry\x18\x02 \x01(\bR\vshouldRetry\"c\n" +
	"\fPushResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.message.v1.PushStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"j\n" +
	"\x10BatchPushRequest\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.message.v1.PushMessageR\bmessages\x12!\n" +
	"\fcallback_url\x18\x02 \x01(\tR\vcallbackUrl\"z\n" +
	"\x11BatchPushResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12%\n" +
	"\x0eaccepted_count\x18\x02 \x01(\x05R\racceptedCount\x12%\n" +
	"\x0erejected_count\x18\x03 \x01(\x05R\rrejectedCount*\xbf\x01\n" +
	"\n" +
	"PushStatus\x12\x1b\n" +
	"\x17PUSH_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PUSH_STATUS_SUCCESS\x10\x01\x12\x1c\n" +
	"\x18PUSH_STATUS_USER_OFFLINE\x10\x02\x12\x1c\n" +
	"\x18PUSH_STATUS_RATE_LIMITED\x10\x03\x12\x1f\n" +
	"\x1bPUSH_STATUS_INVALID_MESSAGE\x10\x04\x12\x1e\n" +
	"\x1aPUSH_STATUS_INTERNAL_ERROR\x10\x052\x92\x01\n" +
	"\vPushService\x129\n" +
	"\x04Push\x12\x17.message.v1.PushRequest\x1a\x18.message.v1.PushResponse\x12H\n" +
	"\tBatchPush\x12\x1c.message.v1.BatchPushRequest\x1a\x1d.message.v1.BatchPushResponseB\xa1\x01\n" +
	"\x0ecom.message.v1B\fMessageProtoP\x01Z8github.com/jrmarcco/synp-api/api/go/message/v1;messagev1\xa2\x02\x03MXX\xaa\x02\n" +
	"Message.V1\xca\x02\n" +
	"Message\\V1\xe2\x02\x16Message\\V1\\GPBMetadata\xea\x02\vMessage::V1b\x06proto3"

var (
	file_message_v1_message_proto_rawDescOnce sync.Once
	file_message_v1_message_proto_rawDescData []byte
)

func file_message_v1_message_proto_rawDescGZIP() []byte {
	file_message_v1_message_proto_rawDescOnce.Do(func() {
		file_message_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_v1_message_proto_rawDesc), len(file_message_v1_message_proto_rawDesc)))
	})
	return file_message_v1_message_proto_rawDescData
}

var file_message_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_message_v1_message_proto_goTypes = []any{
	(PushStatus)(0),           // 0: message.v1.PushStatus
	(*Message)(nil),           // 1: message.v1.Message
	(*AckPayload)(nil),        // 2: message.v1.AckPayload
	(*PushMessage)(nil),       // 3: message.v1.PushMessage
	(*PushRequest)(nil),       // 4: message.v1.PushRequest
	(*PushResponse)(nil),      // 5: message.v1.PushResponse
	(*BatchPushRequest)(nil),  // 6: message.v1.BatchPushRequest
	(*BatchPushResponse)(nil), // 7: message.v1.BatchPushResponse
	(v1.CommandType)(0),       // 8: common.v1.CommandType
	(v1.SerializeType)(0),     // 9: common.v1.SerializeType
}
var file_message_v1_message_proto_depIdxs = []int32{
	8, // 0: message.v1.Message.command_type:type_name -> common.v1.CommandType
	9, // 1: message.v1.Message.serialize_type:type_name -> common.v1.SerializeType
	9, // 2: message.v1.PushMessage.serialize_type:type_name -> common.v1.SerializeType
	3, // 3: message.v1.PushRequest.message:type_name -> message.v1.PushMessage
	0, // 4: message.v1.PushResponse.status:type_name -> message.v1.PushStatus
	3, // 5: message.v1.BatchPushRequest.messages:type_name -> message.v1.PushMessage
	4, // 6: message.v1.PushService.Push:input_type -> message.v1.PushRequest
	6, // 7: message.v1.PushService.BatchPush:input_type -> message.v1.BatchPushRequest
	5, // 8: message.v1.PushService.Push:output_type -> message.v1.PushResponse
	7, // 9: message.v1.PushService.BatchPush:output_type -> message.v1.BatchPushResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_message_v1_message_proto_init() }
func file_message_v1_message_proto_init() {
	if File_message_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_v1_message_proto_rawDesc), len(file_message_v1_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_v1_message_proto_goTypes,
		DependencyIndexes: file_message_v1_message_proto_depIdxs,
		EnumInfos:         file_message_v1_message_proto_enumTypes,
		MessageInfos:      file_message_v1_message_proto_msgTypes,
	}.Build()
	File_message_v1_message_proto = out.File
	file_message_v1_message_proto_goTypes = nil
	file_message_v1_message_proto_depIdxs = nil
}
