// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: message/v1/message.proto

package messagev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	commonv1 "github.com/jrmarcco/synp-api/api/go/common/v1"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = commonv1.CommandType(0)
)

// Validate checks the field values on Message with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Message) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Message with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MessageMultiError, or nil if none found.
func (m *Message) ValidateAll() error {
	return m.validate(true)
}

func (m *Message) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CommandType

	// no validation rules for MessageId

	// no validation rules for SerializeType

	// no validation rules for Body

	if len(errors) > 0 {
		return MessageMultiError(errors)
	}

	return nil
}

// MessageMultiError is an error wrapping multiple validation errors returned
// by Message.ValidateAll() if the designated constraints aren't met.
type MessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageMultiError) AllErrors() []error { return m }

// MessageValidationError is the validation error returned by Message.Validate
// if the designated constraints aren't met.
type MessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageValidationError) ErrorName() string { return "MessageValidationError" }

// Error satisfies the builtin error interface
func (e MessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageValidationError{}

// Validate checks the field values on AckPayload with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AckPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AckPayload with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AckPayloadMultiError, or
// nil if none found.
func (m *AckPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *AckPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsSuccess

	// no validation rules for TimestampMs

	// no validation rules for ErrorMessage

	if len(errors) > 0 {
		return AckPayloadMultiError(errors)
	}

	return nil
}

// AckPayloadMultiError is an error wrapping multiple validation errors
// returned by AckPayload.ValidateAll() if the designated constraints aren't met.
type AckPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AckPayloadMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AckPayloadMultiError) AllErrors() []error { return m }

// AckPayloadValidationError is the validation error returned by
// AckPayload.Validate if the designated constraints aren't met.
type AckPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AckPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AckPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AckPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AckPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AckPayloadValidationError) ErrorName() string { return "AckPayloadValidationError" }

// Error satisfies the builtin error interface
func (e AckPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAckPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AckPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AckPayloadValidationError{}

// Validate checks the field values on PushMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PushMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PushMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PushMessageMultiError, or
// nil if none found.
func (m *PushMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *PushMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MessageId

	// no validation rules for BusinessId

	// no validation rules for ReceiverId

	// no validation rules for SerializeType

	// no validation rules for Body

	if len(errors) > 0 {
		return PushMessageMultiError(errors)
	}

	return nil
}

// PushMessageMultiError is an error wrapping multiple validation errors
// returned by PushMessage.ValidateAll() if the designated constraints aren't met.
type PushMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PushMessageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PushMessageMultiError) AllErrors() []error { return m }

// PushMessageValidationError is the validation error returned by
// PushMessage.Validate if the designated constraints aren't met.
type PushMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PushMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PushMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PushMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PushMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PushMessageValidationError) ErrorName() string { return "PushMessageValidationError" }

// Error satisfies the builtin error interface
func (e PushMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPushMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PushMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PushMessageValidationError{}

// Validate checks the field values on PushRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PushRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PushRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PushRequestMultiError, or
// nil if none found.
func (m *PushRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PushRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetMessage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PushRequestValidationError{
					field:  "Message",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PushRequestValidationError{
					field:  "Message",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMessage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PushRequestValidationError{
				field:  "Message",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ShouldRetry

	if len(errors) > 0 {
		return PushRequestMultiError(errors)
	}

	return nil
}

// PushRequestMultiError is an error wrapping multiple validation errors
// returned by PushRequest.ValidateAll() if the designated constraints aren't met.
type PushRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PushRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PushRequestMultiError) AllErrors() []error { return m }

// PushRequestValidationError is the validation error returned by
// PushRequest.Validate if the designated constraints aren't met.
type PushRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PushRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PushRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PushRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PushRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PushRequestValidationError) ErrorName() string { return "PushRequestValidationError" }

// Error satisfies the builtin error interface
func (e PushRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPushRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PushRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PushRequestValidationError{}

// Validate checks the field values on PushResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PushResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PushResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PushResponseMultiError, or
// nil if none found.
func (m *PushResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PushResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	// no validation rules for ErrorMessage

	if len(errors) > 0 {
		return PushResponseMultiError(errors)
	}

	return nil
}

// PushResponseMultiError is an error wrapping multiple validation errors
// returned by PushResponse.ValidateAll() if the designated constraints aren't met.
type PushResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PushResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PushResponseMultiError) AllErrors() []error { return m }

// PushResponseValidationError is the validation error returned by
// PushResponse.Validate if the designated constraints aren't met.
type PushResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PushResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PushResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PushResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PushResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PushResponseValidationError) ErrorName() string { return "PushResponseValidationError" }

// Error satisfies the builtin error interface
func (e PushResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPushResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PushResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PushResponseValidationError{}

// Validate checks the field values on BatchPushRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BatchPushRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BatchPushRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BatchPushRequestMultiError, or nil if none found.
func (m *BatchPushRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BatchPushRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetMessages() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BatchPushRequestValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BatchPushRequestValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BatchPushRequestValidationError{
					field:  fmt.Sprintf("Messages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for CallbackUrl

	if len(errors) > 0 {
		return BatchPushRequestMultiError(errors)
	}

	return nil
}

// BatchPushRequestMultiError is an error wrapping multiple validation errors
// returned by BatchPushRequest.ValidateAll() if the designated constraints
// aren't met.
type BatchPushRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BatchPushRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BatchPushRequestMultiError) AllErrors() []error { return m }

// BatchPushRequestValidationError is the validation error returned by
// BatchPushRequest.Validate if the designated constraints aren't met.
type BatchPushRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BatchPushRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BatchPushRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BatchPushRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BatchPushRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BatchPushRequestValidationError) ErrorName() string { return "BatchPushRequestValidationError" }

// Error satisfies the builtin error interface
func (e BatchPushRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBatchPushRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BatchPushRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BatchPushRequestValidationError{}

// Validate checks the field values on BatchPushResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BatchPushResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BatchPushResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BatchPushResponseMultiError, or nil if none found.
func (m *BatchPushResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BatchPushResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	// no validation rules for AcceptedCount

	// no validation rules for RejectedCount

	if len(errors) > 0 {
		return BatchPushResponseMultiError(errors)
	}

	return nil
}

// BatchPushResponseMultiError is an error wrapping multiple validation errors
// returned by BatchPushResponse.ValidateAll() if the designated constraints
// aren't met.
type BatchPushResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BatchPushResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BatchPushResponseMultiError) AllErrors() []error { return m }

// BatchPushResponseValidationError is the validation error returned by
// BatchPushResponse.Validate if the designated constraints aren't met.
type BatchPushResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BatchPushResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BatchPushResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BatchPushResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BatchPushResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BatchPushResponseValidationError) ErrorName() string {
	return "BatchPushResponseValidationError"
}

// Error satisfies the builtin error interface
func (e BatchPushResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBatchPushResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BatchPushResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BatchPushResponseValidationError{}
