// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: route/v1/route.proto

package routev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Node with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Node) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Node with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in NodeMultiError, or nil if none found.
func (m *Node) ValidateAll() error {
	return m.validate(true)
}

func (m *Node) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ClusterId

	// no validation rules for ServiceName

	// no validation rules for ServiceAddress

	if len(errors) > 0 {
		return NodeMultiError(errors)
	}

	return nil
}

// NodeMultiError is an error wrapping multiple validation errors returned by
// Node.ValidateAll() if the designated constraints aren't met.
type NodeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NodeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NodeMultiError) AllErrors() []error { return m }

// NodeValidationError is the validation error returned by Node.Validate if the
// designated constraints aren't met.
type NodeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NodeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NodeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NodeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NodeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NodeValidationError) ErrorName() string { return "NodeValidationError" }

// Error satisfies the builtin error interface
func (e NodeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNode.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NodeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NodeValidationError{}

// Validate checks the field values on UserConnection with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserConnection) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserConnection with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserConnectionMultiError,
// or nil if none found.
func (m *UserConnection) ValidateAll() error {
	return m.validate(true)
}

func (m *UserConnection) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BusinessId

	// no validation rules for UserId

	if all {
		switch v := interface{}(m.GetNode()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserConnectionValidationError{
					field:  "Node",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserConnectionValidationError{
					field:  "Node",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNode()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserConnectionValidationError{
				field:  "Node",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ConnectionId

	// no validation rules for DeviceType

	if all {
		switch v := interface{}(m.GetConnectedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserConnectionValidationError{
					field:  "ConnectedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserConnectionValidationError{
					field:  "ConnectedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConnectedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserConnectionValidationError{
				field:  "ConnectedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UserConnectionMultiError(errors)
	}

	return nil
}

// UserConnectionMultiError is an error wrapping multiple validation errors
// returned by UserConnection.ValidateAll() if the designated constraints
// aren't met.
type UserConnectionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserConnectionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserConnectionMultiError) AllErrors() []error { return m }

// UserConnectionValidationError is the validation error returned by
// UserConnection.Validate if the designated constraints aren't met.
type UserConnectionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserConnectionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserConnectionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserConnectionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserConnectionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserConnectionValidationError) ErrorName() string { return "UserConnectionValidationError" }

// Error satisfies the builtin error interface
func (e UserConnectionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserConnection.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserConnectionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserConnectionValidationError{}

// Validate checks the field values on RegisterConnectionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterConnectionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterConnectionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterConnectionRequestMultiError, or nil if none found.
func (m *RegisterConnectionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterConnectionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetConnection()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegisterConnectionRequestValidationError{
					field:  "Connection",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegisterConnectionRequestValidationError{
					field:  "Connection",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConnection()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegisterConnectionRequestValidationError{
				field:  "Connection",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for TtlSeconds

	if len(errors) > 0 {
		return RegisterConnectionRequestMultiError(errors)
	}

	return nil
}

// RegisterConnectionRequestMultiError is an error wrapping multiple validation
// errors returned by RegisterConnectionRequest.ValidateAll() if the
// designated constraints aren't met.
type RegisterConnectionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterConnectionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterConnectionRequestMultiError) AllErrors() []error { return m }

// RegisterConnectionRequestValidationError is the validation error returned by
// RegisterConnectionRequest.Validate if the designated constraints aren't met.
type RegisterConnectionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterConnectionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterConnectionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterConnectionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterConnectionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterConnectionRequestValidationError) ErrorName() string {
	return "RegisterConnectionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterConnectionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterConnectionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterConnectionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterConnectionRequestValidationError{}

// Validate checks the field values on RegisterConnectionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterConnectionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterConnectionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterConnectionResponseMultiError, or nil if none found.
func (m *RegisterConnectionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterConnectionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRegisteredAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegisterConnectionResponseValidationError{
					field:  "RegisteredAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegisterConnectionResponseValidationError{
					field:  "RegisteredAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRegisteredAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegisterConnectionResponseValidationError{
				field:  "RegisteredAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetExpiresAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegisterConnectionResponseValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegisterConnectionResponseValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpiresAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegisterConnectionResponseValidationError{
				field:  "ExpiresAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RegisterConnectionResponseMultiError(errors)
	}

	return nil
}

// RegisterConnectionResponseMultiError is an error wrapping multiple
// validation errors returned by RegisterConnectionResponse.ValidateAll() if
// the designated constraints aren't met.
type RegisterConnectionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterConnectionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterConnectionResponseMultiError) AllErrors() []error { return m }

// RegisterConnectionResponseValidationError is the validation error returned
// by RegisterConnectionResponse.Validate if the designated constraints aren't met.
type RegisterConnectionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterConnectionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterConnectionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterConnectionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterConnectionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterConnectionResponseValidationError) ErrorName() string {
	return "RegisterConnectionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterConnectionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterConnectionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterConnectionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterConnectionResponseValidationError{}

// Validate checks the field values on GetUserConnectionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserConnectionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserConnectionsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserConnectionsRequestMultiError, or nil if none found.
func (m *GetUserConnectionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserConnectionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BusinessId

	// no validation rules for UserId

	if len(errors) > 0 {
		return GetUserConnectionsRequestMultiError(errors)
	}

	return nil
}

// GetUserConnectionsRequestMultiError is an error wrapping multiple validation
// errors returned by GetUserConnectionsRequest.ValidateAll() if the
// designated constraints aren't met.
type GetUserConnectionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserConnectionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserConnectionsRequestMultiError) AllErrors() []error { return m }

// GetUserConnectionsRequestValidationError is the validation error returned by
// GetUserConnectionsRequest.Validate if the designated constraints aren't met.
type GetUserConnectionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserConnectionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserConnectionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserConnectionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserConnectionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserConnectionsRequestValidationError) ErrorName() string {
	return "GetUserConnectionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserConnectionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserConnectionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserConnectionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserConnectionsRequestValidationError{}

// Validate checks the field values on GetUserConnectionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserConnectionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserConnectionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserConnectionsResponseMultiError, or nil if none found.
func (m *GetUserConnectionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserConnectionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetConnections() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetUserConnectionsResponseValidationError{
						field:  fmt.Sprintf("Connections[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetUserConnectionsResponseValidationError{
						field:  fmt.Sprintf("Connections[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetUserConnectionsResponseValidationError{
					field:  fmt.Sprintf("Connections[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetUserConnectionsResponseMultiError(errors)
	}

	return nil
}

// GetUserConnectionsResponseMultiError is an error wrapping multiple
// validation errors returned by GetUserConnectionsResponse.ValidateAll() if
// the designated constraints aren't met.
type GetUserConnectionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserConnectionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserConnectionsResponseMultiError) AllErrors() []error { return m }

// GetUserConnectionsResponseValidationError is the validation error returned
// by GetUserConnectionsResponse.Validate if the designated constraints aren't met.
type GetUserConnectionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserConnectionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserConnectionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserConnectionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserConnectionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserConnectionsResponseValidationError) ErrorName() string {
	return "GetUserConnectionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserConnectionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserConnectionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserConnectionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserConnectionsResponseValidationError{}
