// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: route/v1/route.proto

package routev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeviceType 表示用户设备类型。
type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_UNSPECIFIED DeviceType = 0
	DeviceType_DEVICE_TYPE_MOBILE      DeviceType = 1
	DeviceType_DEVICE_TYPE_TABLET      DeviceType = 2
	DeviceType_DEVICE_TYPE_PC          DeviceType = 3
	DeviceType_DEVICE_TYPE_UNKNOWN     DeviceType = 4
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "DEVICE_TYPE_MOBILE",
		2: "DEVICE_TYPE_TABLET",
		3: "DEVICE_TYPE_PC",
		4: "DEVICE_TYPE_UNKNOWN",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"DEVICE_TYPE_MOBILE":      1,
		"DEVICE_TYPE_TABLET":      2,
		"DEVICE_TYPE_PC":          3,
		"DEVICE_TYPE_UNKNOWN":     4,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_route_v1_route_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_route_v1_route_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_route_v1_route_proto_rawDescGZIP(), []int{0}
}

// Node 是用户所连接的网关节点信息。
type Node struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClusterId string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// service_name 和 service_address 用于服务发现或直接访问网关节点。
	ServiceName    string `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceAddress string `protobuf:"bytes,4,opt,name=service_address,json=serviceAddress,proto3" json:"service_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_route_v1_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_route_v1_route_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Node) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Node) GetServiceAddress() string {
	if x != nil {
		return x.ServiceAddress
	}
	return ""
}

// UserConnection 表示一条用户连接及其所在网关节点。
type UserConnection struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BusinessId uint64                 `protobuf:"varint,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	UserId     uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Node       *Node                  `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	// connection_id 由网关生成，在同一业务内唯一。
	ConnectionId  string                 `protobuf:"bytes,4,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	DeviceType    DeviceType             `protobuf:"varint,5,opt,name=device_type,json=deviceType,proto3,enum=route.v1.DeviceType" json:"device_type,omitempty"`
	ConnectedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConnection) Reset() {
	*x = UserConnection{}
	mi := &file_route_v1_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConnection) ProtoMessage() {}

func (x *UserConnection) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConnection.ProtoReflect.Descriptor instead.
func (*UserConnection) Descriptor() ([]byte, []int) {
	return file_route_v1_route_proto_rawDescGZIP(), []int{1}
}

func (x *UserConnection) GetBusinessId() uint64 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *UserConnection) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserConnection) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *UserConnection) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *UserConnection) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *UserConnection) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

type RegisterConnectionRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Connection *UserConnection        `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	// ttl_seconds 是路由记录的有效期。网关可通过重复注册刷新有效期。
	TtlSeconds    uint32 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConnectionRequest) Reset() {
	*x = RegisterConnectionRequest{}
	mi := &file_route_v1_route_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConnectionRequest) ProtoMessage() {}

func (x *RegisterConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_route_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConnectionRequest.ProtoReflect.Descriptor instead.
func (*RegisterConnectionRequest) Descriptor() ([]byte, []int) {
	return file_route_v1_route_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterConnectionRequest) GetConnection() *UserConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *RegisterConnectionRequest) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type RegisterConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConnectionResponse) Reset() {
	*x = RegisterConnectionResponse{}
	mi := &file_route_v1_route_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConnectionResponse) ProtoMessage() {}

func (x *RegisterConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_route_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConnectionResponse.ProtoReflect.Descriptor instead.
func (*RegisterConnectionResponse) Descriptor() ([]byte, []int) {
	return file_route_v1_route_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterConnectionResponse) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *RegisterConnectionResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type GetUserConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessId    uint64                 `protobuf:"varint,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserConnectionsRequest) Reset() {
	*x = GetUserConnectionsRequest{}
	mi := &file_route_v1_route_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConnectionsRequest) ProtoMessage() {}

func (x *GetUserConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_route_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConnectionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_route_v1_route_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserConnectionsRequest) GetBusinessId() uint64 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *GetUserConnectionsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserConnectionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connections 支持同一用户同时连接多个设备或网关节点。
	Connections   []*UserConnection `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserConnectionsResponse) Reset() {
	*x = GetUserConnectionsResponse{}
	mi := &file_route_v1_route_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConnectionsResponse) ProtoMessage() {}

func (x *GetUserConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_route_v1_route_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConnectionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_route_v1_route_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserConnectionsResponse) GetConnections() []*UserConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

var File_route_v1_route_proto protoreflect.FileDescriptor

const file_route_v1_route_proto_rawDesc = "" +
	"\n" +
	"\x14route/v1/route.proto\x12\broute.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_address\x18\x04 \x01(\tR\x0eserviceAddress\"\x89\x02\n" +
	"\x0eUserConnection\x12\x1f\n" +
	"\vbusiness_id\x18\x01 \x01(\x04R\n" +
	"businessId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\"\n" +
	"\x04node\x18\x03 \x01(\v2\x0e.route.v1.NodeR\x04node\x12#\n" +
	"\rconnection_id\x18\x04 \x01(\tR\fconnectionId\x125\n" +
	"\vdevice_type\x18\x05 \x01(\x0e2\x14.route.v1.DeviceTypeR\n" +
	"deviceType\x12=\n" +
	"\fconnected_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\"v\n" +
	"\x19RegisterConnectionRequest\x128\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\x18.route.v1.UserConnectionR\n" +
	"connection\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\rR\n" +
	"ttlSeconds\"\x98\x01\n" +
	"\x1aRegisterConnectionResponse\x12?\n" +
	"\rregistered_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"U\n" +
	"\x19GetUserConnectionsRequest\x12\x1f\n" +
	"\vbusiness_id\x18\x01 \x01(\x04R\n" +
	"businessId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"X\n" +
	"\x1aGetUserConnectionsResponse\x12:\n" +
	"\vconnections\x18\x01 \x03(\v2\x18.route.v1.UserConnectionR\vconnections*\x86\x01\n" +
	"\n" +
	"DeviceType\x12\x1b\n" +
	"\x17DEVICE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DEVICE_TYPE_MOBILE\x10\x01\x12\x16\n" +
	"\x12DEVICE_TYPE_TABLET\x10\x02\x12\x12\n" +
	"\x0eDEVICE_TYPE_PC\x10\x03\x12\x17\n" +
	"\x13DEVICE_TYPE_UNKNOWN\x10\x042\xd0\x01\n" +
	"\fRouteService\x12_\n" +
	"\x12RegisterConnection\x12#.route.v1.RegisterConnectionRequest\x1a$.route.v1.RegisterConnectionResponse\x12_\n" +
	"\x12GetUserConnections\x12#.route.v1.GetUserConnectionsRequest\x1a$.route.v1.GetUserConnectionsResponseB\x90\x01\n" +
	"\fcom.route.v1B\n" +
	"RouteProtoP\x01Z3github.com/jrmarcco/synpapi/api/go/route/v1;routev1\xa2\x02\x03RXX\xaa\x02\bRoute.V1\xca\x02\bRoute\\V1\xe2\x02\x14Route\\V1\\GPBMetadata\xea\x02\tRoute::V1b\x06proto3"

var (
	file_route_v1_route_proto_rawDescOnce sync.Once
	file_route_v1_route_proto_rawDescData []byte
)

func file_route_v1_route_proto_rawDescGZIP() []byte {
	file_route_v1_route_proto_rawDescOnce.Do(func() {
		file_route_v1_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_route_v1_route_proto_rawDesc), len(file_route_v1_route_proto_rawDesc)))
	})
	return file_route_v1_route_proto_rawDescData
}

var file_route_v1_route_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_route_v1_route_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_route_v1_route_proto_goTypes = []any{
	(DeviceType)(0),                    // 0: route.v1.DeviceType
	(*Node)(nil),                       // 1: route.v1.Node
	(*UserConnection)(nil),             // 2: route.v1.UserConnection
	(*RegisterConnectionRequest)(nil),  // 3: route.v1.RegisterConnectionRequest
	(*RegisterConnectionResponse)(nil), // 4: route.v1.RegisterConnectionResponse
	(*GetUserConnectionsRequest)(nil),  // 5: route.v1.GetUserConnectionsRequest
	(*GetUserConnectionsResponse)(nil), // 6: route.v1.GetUserConnectionsResponse
	(*timestamppb.Timestamp)(nil),      // 7: google.protobuf.Timestamp
}
var file_route_v1_route_proto_depIdxs = []int32{
	1, // 0: route.v1.UserConnection.node:type_name -> route.v1.Node
	0, // 1: route.v1.UserConnection.device_type:type_name -> route.v1.DeviceType
	7, // 2: route.v1.UserConnection.connected_at:type_name -> google.protobuf.Timestamp
	2, // 3: route.v1.RegisterConnectionRequest.connection:type_name -> route.v1.UserConnection
	7, // 4: route.v1.RegisterConnectionResponse.registered_at:type_name -> google.protobuf.Timestamp
	7, // 5: route.v1.RegisterConnectionResponse.expires_at:type_name -> google.protobuf.Timestamp
	2, // 6: route.v1.GetUserConnectionsResponse.connections:type_name -> route.v1.UserConnection
	3, // 7: route.v1.RouteService.RegisterConnection:input_type -> route.v1.RegisterConnectionRequest
	5, // 8: route.v1.RouteService.GetUserConnections:input_type -> route.v1.GetUserConnectionsRequest
	4, // 9: route.v1.RouteService.RegisterConnection:output_type -> route.v1.RegisterConnectionResponse
	6, // 10: route.v1.RouteService.GetUserConnections:output_type -> route.v1.GetUserConnectionsResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_route_v1_route_proto_init() }
func file_route_v1_route_proto_init() {
	if File_route_v1_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_route_v1_route_proto_rawDesc), len(file_route_v1_route_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_route_v1_route_proto_goTypes,
		DependencyIndexes: file_route_v1_route_proto_depIdxs,
		EnumInfos:         file_route_v1_route_proto_enumTypes,
		MessageInfos:      file_route_v1_route_proto_msgTypes,
	}.Build()
	File_route_v1_route_proto = out.File
	file_route_v1_route_proto_goTypes = nil
	file_route_v1_route_proto_depIdxs = nil
}
