// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: node/v1/locate.proto

package nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceAddr   string                 `protobuf:"bytes,2,opt,name=service_addr,json=serviceAddr,proto3" json:"service_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLocation) Reset() {
	*x = UserLocation{}
	mi := &file_node_v1_locate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLocation) ProtoMessage() {}

func (x *UserLocation) ProtoReflect() protoreflect.Message {
	mi := &file_node_v1_locate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLocation.ProtoReflect.Descriptor instead.
func (*UserLocation) Descriptor() ([]byte, []int) {
	return file_node_v1_locate_proto_rawDescGZIP(), []int{0}
}

func (x *UserLocation) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UserLocation) GetServiceAddr() string {
	if x != nil {
		return x.ServiceAddr
	}
	return ""
}

type LocateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         uint64                 `protobuf:"varint,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateUserRequest) Reset() {
	*x = LocateUserRequest{}
	mi := &file_node_v1_locate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateUserRequest) ProtoMessage() {}

func (x *LocateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_v1_locate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateUserRequest.ProtoReflect.Descriptor instead.
func (*LocateUserRequest) Descriptor() ([]byte, []int) {
	return file_node_v1_locate_proto_rawDescGZIP(), []int{1}
}

func (x *LocateUserRequest) GetBizId() uint64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *LocateUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LocateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*UserLocation        `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateUserResponse) Reset() {
	*x = LocateUserResponse{}
	mi := &file_node_v1_locate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateUserResponse) ProtoMessage() {}

func (x *LocateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_v1_locate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateUserResponse.ProtoReflect.Descriptor instead.
func (*LocateUserResponse) Descriptor() ([]byte, []int) {
	return file_node_v1_locate_proto_rawDescGZIP(), []int{2}
}

func (x *LocateUserResponse) GetLocations() []*UserLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

var File_node_v1_locate_proto protoreflect.FileDescriptor

const file_node_v1_locate_proto_rawDesc = "" +
	"\n" +
	"\x14node/v1/locate.proto\x12\anode.v1\"T\n" +
	"\fUserLocation\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12!\n" +
	"\fservice_addr\x18\x02 \x01(\tR\vserviceAddr\"C\n" +
	"\x11LocateUserRequest\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\x04R\x05bizId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"I\n" +
	"\x12LocateUserResponse\x123\n" +
	"\tlocations\x18\x01 \x03(\v2\x15.node.v1.UserLocationR\tlocations2V\n" +
	"\rLocateService\x12E\n" +
	"\n" +
	"LocateUser\x12\x1a.node.v1.LocateUserRequest\x1a\x1b.node.v1.LocateUserResponseB\x8b\x01\n" +
	"\vcom.node.v1B\vLocateProtoP\x01Z2github.com/jrmarcco/synp-api/api/go/node/v1;nodev1\xa2\x02\x03NXX\xaa\x02\aNode.V1\xca\x02\aNode\\V1\xe2\x02\x13Node\\V1\\GPBMetadata\xea\x02\bNode::V1b\x06proto3"

var (
	file_node_v1_locate_proto_rawDescOnce sync.Once
	file_node_v1_locate_proto_rawDescData []byte
)

func file_node_v1_locate_proto_rawDescGZIP() []byte {
	file_node_v1_locate_proto_rawDescOnce.Do(func() {
		file_node_v1_locate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_v1_locate_proto_rawDesc), len(file_node_v1_locate_proto_rawDesc)))
	})
	return file_node_v1_locate_proto_rawDescData
}

var file_node_v1_locate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_node_v1_locate_proto_goTypes = []any{
	(*UserLocation)(nil),       // 0: node.v1.UserLocation
	(*LocateUserRequest)(nil),  // 1: node.v1.LocateUserRequest
	(*LocateUserResponse)(nil), // 2: node.v1.LocateUserResponse
}
var file_node_v1_locate_proto_depIdxs = []int32{
	0, // 0: node.v1.LocateUserResponse.locations:type_name -> node.v1.UserLocation
	1, // 1: node.v1.LocateService.LocateUser:input_type -> node.v1.LocateUserRequest
	2, // 2: node.v1.LocateService.LocateUser:output_type -> node.v1.LocateUserResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_node_v1_locate_proto_init() }
func file_node_v1_locate_proto_init() {
	if File_node_v1_locate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_v1_locate_proto_rawDesc), len(file_node_v1_locate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_v1_locate_proto_goTypes,
		DependencyIndexes: file_node_v1_locate_proto_depIdxs,
		MessageInfos:      file_node_v1_locate_proto_msgTypes,
	}.Build()
	File_node_v1_locate_proto = out.File
	file_node_v1_locate_proto_goTypes = nil
	file_node_v1_locate_proto_depIdxs = nil
}
