// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: node/v1/locate.proto

package nodev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocateService_LocateUser_FullMethodName = "/node.v1.LocateService/LocateUser"
)

// LocateServiceClient is the client API for LocateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LocateService 提供用户连接网关节点的查询能力。
type LocateServiceClient interface {
	LocateUser(ctx context.Context, in *LocateUserRequest, opts ...grpc.CallOption) (*LocateUserResponse, error)
}

type locateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocateServiceClient(cc grpc.ClientConnInterface) LocateServiceClient {
	return &locateServiceClient{cc}
}

func (c *locateServiceClient) LocateUser(ctx context.Context, in *LocateUserRequest, opts ...grpc.CallOption) (*LocateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocateUserResponse)
	err := c.cc.Invoke(ctx, LocateService_LocateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocateServiceServer is the server API for LocateService service.
// All implementations should embed UnimplementedLocateServiceServer
// for forward compatibility.
//
// LocateService 提供用户连接网关节点的查询能力。
type LocateServiceServer interface {
	LocateUser(context.Context, *LocateUserRequest) (*LocateUserResponse, error)
}

// UnimplementedLocateServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocateServiceServer struct{}

func (UnimplementedLocateServiceServer) LocateUser(context.Context, *LocateUserRequest) (*LocateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LocateUser not implemented")
}
func (UnimplementedLocateServiceServer) testEmbeddedByValue() {}

// UnsafeLocateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocateServiceServer will
// result in compilation errors.
type UnsafeLocateServiceServer interface {
	mustEmbedUnimplementedLocateServiceServer()
}

func RegisterLocateServiceServer(s grpc.ServiceRegistrar, srv LocateServiceServer) {
	// If the following call panics, it indicates UnimplementedLocateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocateService_ServiceDesc, srv)
}

func _LocateService_LocateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocateServiceServer).LocateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocateService_LocateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocateServiceServer).LocateUser(ctx, req.(*LocateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocateService_ServiceDesc is the grpc.ServiceDesc for LocateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "node.v1.LocateService",
	HandlerType: (*LocateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LocateUser",
			Handler:    _LocateService_LocateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node/v1/locate.proto",
}
