// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: node/v1/locate.proto

package nodev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserLocation with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserLocation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserLocation with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserLocationMultiError, or
// nil if none found.
func (m *UserLocation) ValidateAll() error {
	return m.validate(true)
}

func (m *UserLocation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ServiceName

	// no validation rules for ServiceAddr

	if len(errors) > 0 {
		return UserLocationMultiError(errors)
	}

	return nil
}

// UserLocationMultiError is an error wrapping multiple validation errors
// returned by UserLocation.ValidateAll() if the designated constraints aren't met.
type UserLocationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserLocationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserLocationMultiError) AllErrors() []error { return m }

// UserLocationValidationError is the validation error returned by
// UserLocation.Validate if the designated constraints aren't met.
type UserLocationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserLocationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserLocationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserLocationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserLocationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserLocationValidationError) ErrorName() string { return "UserLocationValidationError" }

// Error satisfies the builtin error interface
func (e UserLocationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserLocation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserLocationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserLocationValidationError{}

// Validate checks the field values on LocateUserRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LocateUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LocateUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LocateUserRequestMultiError, or nil if none found.
func (m *LocateUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LocateUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BusinessId

	// no validation rules for UserId

	if len(errors) > 0 {
		return LocateUserRequestMultiError(errors)
	}

	return nil
}

// LocateUserRequestMultiError is an error wrapping multiple validation errors
// returned by LocateUserRequest.ValidateAll() if the designated constraints
// aren't met.
type LocateUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LocateUserRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LocateUserRequestMultiError) AllErrors() []error { return m }

// LocateUserRequestValidationError is the validation error returned by
// LocateUserRequest.Validate if the designated constraints aren't met.
type LocateUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LocateUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LocateUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LocateUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LocateUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LocateUserRequestValidationError) ErrorName() string {
	return "LocateUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e LocateUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLocateUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LocateUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LocateUserRequestValidationError{}

// Validate checks the field values on LocateUserResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *LocateUserResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LocateUserResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LocateUserResponseMultiError, or nil if none found.
func (m *LocateUserResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *LocateUserResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetLocations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, LocateUserResponseValidationError{
						field:  fmt.Sprintf("Locations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, LocateUserResponseValidationError{
						field:  fmt.Sprintf("Locations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return LocateUserResponseValidationError{
					field:  fmt.Sprintf("Locations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return LocateUserResponseMultiError(errors)
	}

	return nil
}

// LocateUserResponseMultiError is an error wrapping multiple validation errors
// returned by LocateUserResponse.ValidateAll() if the designated constraints
// aren't met.
type LocateUserResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LocateUserResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LocateUserResponseMultiError) AllErrors() []error { return m }

// LocateUserResponseValidationError is the validation error returned by
// LocateUserResponse.Validate if the designated constraints aren't met.
type LocateUserResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LocateUserResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LocateUserResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LocateUserResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LocateUserResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LocateUserResponseValidationError) ErrorName() string {
	return "LocateUserResponseValidationError"
}

// Error satisfies the builtin error interface
func (e LocateUserResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLocateUserResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LocateUserResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LocateUserResponseValidationError{}
